# @package _global_
benchmark_id: YAHPO
task_id: ${task.name}
task:
  _target_: carps.utils.task.Task
  name: yahpo/rbv2_aknn/40975/repl
  seed: ${seed}
  objective_function:
    _target_: carps.objective_functions.yahpo.YahpoObjectiveFunction
    bench: rbv2_aknn
    instance: '40975'
    budget_type: repl
    metric: acc
    seed: ${seed}
  input_space:
    _target_: carps.utils.task.InputSpace
    configuration_space:
      _target_: ConfigSpace.configuration_space.ConfigurationSpace.from_serialized_dict
      _convert_: object
      d:
        name: null
        hyperparameters:
        - type: uniform_int
          name: M
          lower: 18
          upper: 50
          default_value: 34
          log: false
          meta: null
        - type: categorical
          name: distance
          choices:
          - l2
          - cosine
          - ip
          weights: null
          default_value: l2
          meta: null
        - type: uniform_int
          name: ef
          lower: 8
          upper: 256
          default_value: 48
          log: true
          meta: null
        - type: uniform_int
          name: ef_construction
          lower: 8
          upper: 512
          default_value: 96
          log: true
          meta: null
        - type: uniform_int
          name: k
          lower: 1
          upper: 50
          default_value: 26
          log: false
          meta: null
        - type: categorical
          name: num.impute.selected.cpo
          choices:
          - impute.mean
          - impute.median
          - impute.hist
          weights: null
          default_value: impute.mean
          meta: null
        - type: constant
          name: task_id
          value: '40975'
          meta: null
        conditions: []
        forbiddens: []
        python_module_version: 1.2.0
        format_version: 0.4
    fidelity_space:
      _target_: carps.utils.task.FidelitySpace
      is_multifidelity: true
      fidelity_type: repl
      min_fidelity: 1
      max_fidelity: 10
    instance_space: null
  output_space:
    _target_: carps.utils.task.OutputSpace
    n_objectives: 3
    objectives: acc
  optimization_resources:
    _target_: carps.utils.task.OptimizationResources
    n_trials: 118
    time_budget: null
    n_workers: 1
  metadata:
    _target_: carps.utils.task.TaskMetadata
    has_constraints: false
    domain: ML
    objective_function_approximation: surrogate
    has_virtual_time: false
    deterministic: false
    dimensions: 6
    search_space_n_categoricals: 2
    search_space_n_ordinals: 0
    search_space_n_integers: 4
    search_space_n_floats: 0
    search_space_has_conditionals: false
    search_space_has_forbiddens: false
    search_space_has_priors: false
