# @package _global_
benchmark_id: YAHPO
problem_id: yahpo/rbv2_aknn/1478/repl
problem:
  _target_: smacbenchmarking.benchmarks.yahpo.YahpoProblem
  bench: rbv2_aknn
  instance: '1478'
  budget_type: repl
  lower_is_better: false
  metric: acc
task:
  n_trials: 100
  n_objectives: 1
  min_budget: 1
  max_budget: 10
